In [28]:
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
plt.rc("font", size=14)
import seaborn as sns
from scipy.interpolate import spline  
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [79]:
datapath = '../data/'
series_file = datapath + 'fetal_series_02_50.npy'
image_file = datapath + 'fetal_image_02_50_bold.npy'

arr = np.load(datapath + image_file)
# arr1 = f[1, ]
# img = PIL.Image.fromarray(arr)


IOError: [Errno 2] No such file or directory: '../data/../data/fetal_image_02_50_bold.npy'

In [80]:
    f = np.load(series_file)
    x, y = f[0:100, 0:-1], f[0:100, -1:]
    num_data = x.shape[0]
    cols = x.shape[1]
    rows = 200 - 80  # 图像的y轴刻度
    data_mat = np.zeros((num_data, rows * cols), dtype=np.uint8)

    for i in range(num_data):
        if (i % 10 == 0):
            print('i = %s' % i)
        image_mat = np.zeros((rows, cols), dtype=np.uint8)
        for j in range(cols):
            image_mat[x[i][j] - 80][j] = 1
        data_mat[i][:] = np.reshape(image_mat, (1, rows * cols))
    data_label_mat = np.hstack([data_mat, y])

    np.save(image_file, data_label_mat)


i = 0
i = 10
i = 20
i = 30
i = 40
i = 50
i = 60
i = 70
i = 80
i = 90


In [103]:
f = np.load(image_file)
arr = f[:,0:-1]
arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [105]:
arr[arr==0]=255
arr[arr==1]=0
arr

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [125]:
arr1 = np.reshape(arr,(100,120,2402))
label = f[:,-1:]
label_flat = np.reshape(label,(1,100))
str(label_flat[0][0])

'1'

In [135]:
arr1[0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [138]:
for i in range(arr1.shape[0]):
    img = Image.fromarray(np.uint8(arr1[i]))
    path = datapath+'images/'+str(label_flat[0][i])+'_'+str(i)+'.jpg'
    img.save(path)
    

In [ ]:
arr1_test = arr1[0]
arr1_smoth